# Generated by Django 5.1.7 on 2025-03-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_booking_date_booking_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booking_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ticket_code',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='cinemahall',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='price',
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='rows',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.cinemahall')),
            ],
            options={
                'unique_together': {('hall', 'row', 'number')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(to='tickets.seat'),
        ),
    ]
