# Generated by Django 5.1.7 on 2025-03-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_booking_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=6, verbose_name='Цена билета'),
        ),
    ]
