# Generated by Django 5.1.7 on 2025-03-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_showtime_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.TextField(help_text='Перечисление через запятую'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(help_text='Длительность в минутах'),
        ),
    ]
