# Generated by Django 5.1.7 on 2025-03-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=6, verbose_name='Цена места'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP')], default='standard', max_length=20),
        ),
    ]
