# Generated by Django 5.1.7 on 2025-03-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=6, verbose_name='Цена места (₸)'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=6, verbose_name='Цена билета (₸)'),
        ),
    ]
