# Generated by Django 5.1.7 on 2025-03-31 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_seat_price_alter_showtime_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Рекомендуемый фильм'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('scifi', 'Science Fiction'), ('animation', 'Animation'), ('thriller', 'Thriller'), ('romance', 'Romance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='tickets_mov_title_addc48_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='tickets_mov_release_745728_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='tickets_mov_rating_eca72b_idx'),
        ),
    ]
