# Generated by Django 5.1.7 on 2025-03-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_movie_options_movie_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='tickets_mov_title_addc48_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='tickets_mov_release_745728_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='tickets_mov_rating_eca72b_idx',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='tickets.genre'),
        ),
    ]
