# Generated by Django 5.1.7 on 2025-04-02 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_booking_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_refunded',
            field=models.BooleanField(default=False, verbose_name='Возвращен?'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Рейтинг фильма'),
        ),
    ]
