# Generated by Django 5.1.7 on 2025-04-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_remove_movie_is_featured_remove_movie_trailer_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Ссылка на трейлер YouTube', null=True),
        ),
    ]
