# Generated by Django 5.1.7 on 2025-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_cinema_cinemahall_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_type',
            field=models.CharField(choices=[('adult', 'Взрослый'), ('student', 'Студенческий'), ('child', 'Детский')], default='adult', max_length=10),
        ),
    ]
