# Generated by Django 5.1.7 on 2025-04-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_remove_booking_ticket_type_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default='posters/default.jpg', help_text="Path to static image like 'tickets/posters/matrix.jpg'", max_length=200),
            preserve_default=False,
        ),
    ]
